# Final Words
1. La circunferencia $\mathcal{C}=(x-3)^2+()y-3^2=25$ es tangente a una parábola $\mathcal{P}$ en $P_0=(x_0,y_0)$, $y_0>7$. La recta $\mathcal{L}:4x-3y+12=0$ es normal  a $\mathcal{P}$ y $\mathcal{C}$ en $P_0$ y corta al eje focal de $\mathcal{P}$ en el punto $R$ foco de $\mathcal{P}$. Si $\left|\vec{C_0P_0}\right|=\left|\vec{P_0R}\right|$ y si la distancia $d[P_0;eje focal]=4$, hallar la ecuación de la parábola $\mathcal{P}$. $C_0$ es el centro de la circunferencia y la absisa del vértice es menor que 6.

$P_0=C_0\pm r\vec{u}_{\mathcal{L}}$ donde $r=5$, $C_0=(3,8)$ y $\vec{u}_{\mathcal{l}}=\frac{(3,4)}{5}$ es decir $P_0=(3,8)\pm 5\frac{(3,4)}{5}$ de esto consideramos $P_0=(x_0,y_0)=(6,12)$ por condición del problema.

Ya que $\left|\vec{C_0P_0}\right|=5=\left|\vec{P_0R}\right|$ y $d[P_0;eje focal]=d[P_0; R]=4$ entonces el triángulo $P_0QR$ es un triángulo rectángulo notable,  por lo tanto $\left|\vec{QR}\right|=3$ por el Teorema de Pitágoras, además  $\vec{P_0R}=\vec{P_0Q}+\vec{QR}$ es decir si $\vec{P_0Q}=(v_1,v_2)$ se tiene la ecuacion  $(3,4)=4(v_1,v_2)\pm 3(-v_2,v_1)$ que al resolverla se tiene  $\vec{P_0R}=(v_1,v_2)=(1,0)$ o $\vec{P_0R}=(v_1,v_2)=\left(\frac{7}{25},\frac{24}{25}\right)$ entonces $Q=P_0+(0,1)$ o $Q=P_0+\left(\frac{7}{25},\frac{24}{25}\right)$

2. Los puntos $A=(60,13)$ y $B=(-4,61)$ estan sobre una parábola $\mathcal{P}$ además son simétricos con recpecto al eje focal. Desde un punto $Q$ sobre el eje focal se traza un recta tangente a $\mathcal{P}$ que pasa por $B,$ hallar la ecuación de $\mathcal{P}$ y las ecuaciones de las rectas tangentes trazadas desde $Q$.

Ya que $A$ y $B$ son simétricas entonces $P_0=\frac{A+B}{2}=(28,37) \in \mathcal{L}_F$ donde $\mathcal{L}_F$ es el eje focal paralelo al vector $\vec{AB}^\perp=(B-A)^\perp=(-64,48)\parallel(-4,3)=\vec{v}_L$ es decir $\vec{v}_F$ y $P_0$ nos genera la ecuación del eje focal $\mathcal{L}_F:4x+3y=1$. De otro lado dado el punto  $Q=(20,x)\in\mathcal{L}_F$ que al reemplazarlo en la recta del eje focal nos genera $x=-27$ de donde $Q=(20,-27)$ ademas el vértice de la parabola es $V=\frac{Q+P_0}{2}=(4,5)$ por propiedad.

Con el objetivo de hallar el valor de $\rho$ en la ecuación $y'^2=4\rho x'$ se halla las coordenadas de $B$ en el nuevo sistema de coordenadas centrada en $V$ con vector director $\vec{u}=\frac{(3,4)}{5}$, haciendo uso de la relación $$(x,y)=V+x'\vec{u}+y'\vec{u}^\perp$$ se obtiene $x'=\left[B-V\right]\vec{u}=40$ y $y'=\left[B-V\right]\vec{u}^\perp=40$ por tanto reemplazando $B=(-4,61)=(40,40)'$ en $y'^2=4\rho x'$ se tiene que $\rho=10$

Los vectores directores de las rectas tangentes en el sistema $x'y'$ son $(2,1)$ y $(2,-1)$ respectivamente por tanto   sus ecuaciones son $\mathcal{L}_A: 2y'=x'+40$ y $\mathcal{L}_B=-2y'=x'+40$ estas ecuaciones en el sistema original con $x'=\left[(x,y)-(4,5)\right]\frac{(3,4)}{5}$ y  $y'=\left[(x,y)-(4,5)\right]\frac{(-4,3)}{5}$ reemplazadas resultan $\mathcal{L}_A:2y-11x-166=0$ y $\mathcal{L}_B:5x-10y-170=0$ 

1. ww