--- 
title: "Geometría analítica"
author: "MALLQUI BAÑOS Ricardo Michel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: report
fontsize: 12pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Problemas resueltos de Geometría analítica"
subparagraph: yes
---
<!--
git config --global user.email "ricardomallqui6@gmail.com"
git config --global user.name "ricardofisma"
-->
# Algebra vectorial
Sea la la realcion oportuna entre los demas opciones conseguir una de las acciones consistentes de elegirla ecuacion anterior porque se desea que las equivalencias sean congruentes es decir que las deducciones sean logicas y buenas de acuerdo a ls opciones de la gente que debe tener en cuenta las demas opciones congruentes.
## Datos
Sean los datos que se prosiguen

* www
* wwwww

### ff

WWWW fff
WWWW wwwww

### ff

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2_c$.

The **bookdown** package can be installed from CRAN or Github:



Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading .

To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
## Acciones

Sean los datos _emph_ **_real_** **Entonces** 